let product = [
    {
        id: 1001,
        title: "Cat Food, 25lb bag",
        description: "A 25 pound bag of <em>irresistible</em>," + "organic goodness for your cat.",
        price: 2000,
        image: "images/cathouse.jpg",
        availableInventory: 5,
        rating: 1,
    },
    // {
    //     id: 1002,
    //     title: "Yarn",
    //     description: "A ball of yarn your cat can play with.",
    //     price: 1000,
    //     image: "yarn.jpg",
    //     availableInventory: 10,
    //     rating: 5,
    // },
    // {
    //     id: 1003,
    //     title: "Cat House",
    //     description: "A house for your cat to climb and relax.",
    //     price: 5000,
    //     image: "cathouse.jpg",
    //     availableInventory: 2,
    //     rating: 3,
    // },
    // {
    //     id: 1004,
    //     title: "Cat Food, 25lb bag",
    //     description: "A 25 pound bag of <em>irresistible</em>," + "organic goodness for your cat.",
    //     price: 2000,
    //     image: "catfood.jpg",
    //     availableInventory: 5,
    //     rating: 3,
    // },
    // {
    //     id: 1005,
    //     title: "Cat Food, 25lb bag",
    //     description: "A 25 pound bag of <em>irresistible</em>," + "organic goodness for your cat.",
    //     price: 2000,
    //     image: "catfood.jpg",
    //     availableInventory: 5,
    //     rating: 4,
    // }
];