let product = [
    {
        id: 1001,
        title: "Maths Club",
        location: "Dubai",
        price: 2000,
        image: "images/mathsClub.jpg",
        availableSpace: 5,
    },
    {
        id: 1002,
        title: "English Club",
        location: "Dubai",
        price: 1000,
        image: "images/englishClub.jpg",
        availableSpace: 5,
    },
    {
        id: 1003,
        title: "Chemistry Club",
        location: "Dubai",
        price: 5000,
        image: "images/chemClub.jpg",
        availableSpace: 5,
    },
    {
        id: 1004,
        title: "Biology Club",
        location: "Dubai",
        price: 200,
        image: "images/mathsClub.jpg",
        availableSpace: 5,
    },
    {
        id: 1005,
        title: "Physics Club",
        location: "Dubai",
        price: 500,
        image: "images/englishClub.jpg",
        availableSpace: 5,
    },
    {
        id: 1006,
        title: "Music Club",
        location: "Dubai",
        price: 1500,
        image: "images/chemClub.jpg",
        availableSpace: 5,
    },
];